config/routes.rb
Rails.application.routes.draw do
  get 'user/login'

  get 'login/log'

  get 'clockin' => "employee#clockin"
  get 'clockout' => "employee#clockout"
  get 'clockinn' => "managers#clockinn"
  get 'clockoutt' => "managers#clockoutt"

  get 'home/index'
get "managers/clockin" => "managers#clockin"

  resources :managers

  root 'home#index'

end

app/models/manager.rb
class Manager < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected
    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == "admin" && password == "admin"
      end
    end
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  def clockin
  	@managers = Manager.all
  end

  def clockout
  	@managers = Manager.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate, :except => [:managers]
  def index
  end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]
  
  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
     @password = "apple123"
  end

  def

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  def clockinn
    @managers = Manager.all
    
  end

  def clockoutt
    @managers = Manager.all
  end

  def login
    @password = "apple123"
    @input = ""
  end



  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:first_name, :last_name, :age, :gender_string, :mobile_number, :home_number, :job_title, :street_number, :street_name, :suburb, :city, :post_code)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def login
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def time()
		time = Time.new
		time.hour
	end
	def logged_in?
   not request.authorization.nil?
 end

end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/employee/clockin.html.erb
<h1>Clock In</h1>
<div class="sentence">

<p>Please Select your name and Clock In</p>
</div>
<div class="area">
<div class="dropdown">
  
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Employee List
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
    	 <% @managers.each do |manager| %>
    	
      <li class=> <%= manager.first_name %> <%= link_to 'Select', clockinn_path %> </li><br>
     <% end %>
    </ul>
 
  </div>
  </div>


  <div class="buttonss">
  <%= link_to 'Home', root_path, :class => "btn btn-default"%>
</div>

app/views/employee/clockout.html.erb
<h1>Clock out</h1>
<div class="sentence">
<p>Please Select your name and Clock Out</p>
</div>
<div class="area">
<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Employee List
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
    	 <% @managers.each do |manager| %>
    	
      <li class=> <%= manager.first_name %> <%= link_to 'Select', clockoutt_path %> </li><br>
     <% end %>
    </ul>
  </div>
</div>
  <div class="buttonss">
  <%= link_to 'Home', root_path, :class => "btn btn-default"%>
</div>

app/views/home/index.html.erb
<div class="head">
<h1> Welcome to the employee information system </h1>

</div>

<div class="manager-button">

<%= link_to "MANAGER", managers_path, :class => "btn btn-default btn-block", :style => 'color:blue; margin-top:200px;  display: inline-block;' %>

</div>

<div class="employee-button">

<%= link_to "CLOCK IN", clockin_path, :class => "btn btn-default btn-block", :style => 'color:blue; display: inline-block;' %>

</div>

<div class="employee-button">

<%= link_to "CLOCK OUT", clockout_path, :class => "btn btn-default btn-block", :style => 'color:blue;display: inline-block; ' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployeeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/managers/_form.html.erb
<%= form_for(@manager) do |f| %>
  <% if @manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% @manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>      <% end %>
      </ul>
    </div>
  <% end %>


<div class="view-table">
<table class="table table-responsive table-striped table-bordered tab">

  <tr>
    <th>First Name</th>
    <td><%= f.text_field :first_name %></td>
  </tr>
   <tr>
    <th>Last Name</th>
    <td><%= f.text_field :last_name %></td>
  </tr>
 <tr>
    <th>Age</th>
    <td><%= f.number_field :age %></td>
  </tr>
   <tr>
    <th>Gender</th>
    <td><%= f.text_field :gender_string %></td>
  </tr>
   <tr>
    <th>Mobile Number</th> 
    <td><%= f.number_field :mobile_number %></td>
  </tr>
   <tr>
    <th>Home Number</th>
    <td><%= f.number_field :home_number %></td>
  </tr>
   <tr>
    <th>Job Title</th>
    <td><%= f.text_field :job_title %></td>
  </tr>
   <tr>
    <th>Street Number</th>
    <td><%= f.text_field :street_number %></td>
  </tr>
<tr>
    <th>Street Name</th>
    <td><%= f.text_field :street_name %></td>
  </tr>
  <tr>
    <th>Suburb</th>
    <td><%= f.text_field :suburb %></td>
  </tr>
<tr>
    <th>City</th>
    <td><%= f.text_field :city %></td>
  </tr>
  <tr>
    <th>Wage</th>
    <td><%= f.number_field :post_code %></td>
  </tr>

</table>

</div>
  <div class="btn btn-default submits">
    <%= f.submit %>
  </div>

  <% end %>

app/views/managers/clockinn.html.erb
<h1>Successful Clock In</h1>








<%= javascript_tag do %>
 
  var today = new Date();

   
 


function clockin() {
            alert('SUCCESSFUL CLOCK IN AT  ' + today);
        }
        clockin();
        
<% end %>


<%= link_to "RETURN", root_path, :class => "btn btn-default" %>

app/views/managers/clockoutt.html.erb
<h1>Successful Clock Out</h1>


 



<%= javascript_tag do %>
 
  var today = new Date();

   
 


function clockout() {
            alert('SUCCESSFUL CLOCK OUT AT  ' + today);
        }
        clockout();
        
<% end %>


<%= link_to "RETURN", root_path, :class => "btn btn-default" %>

app/views/managers/edit.html.erb
<h1>Editing <%= @manager.first_name %></h1>

<%= render 'form' %>

app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>
<div class="table-responsive">
<table class="table table-hover table-bordered view">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Gender </th>
      <th>Mobile number</th>
      <th>Home number</th>
      <th>Job title</th>
      <th>Street number</th>
      <th>Street name</th>
      <th>Suburb</th>
      <th>City</th>
      <th>Wage</th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= manager.first_name %></td>
        <td><%= manager.last_name %></td>
        <td><%= manager.age %></td>
        <td><%= manager.gender_string %></td>
        <td><%= manager.mobile_number %></td>
        <td><%= manager.home_number %></td>
        <td><%= manager.job_title %></td>
        <td><%= manager.street_number %></td>
        <td><%= manager.street_name %></td>
        <td><%= manager.suburb %></td>
        <td><%= manager.city %></td>
        <td><%= manager.post_code %></td>
        <td><%= link_to 'View', manager, :class => "btn-xs btn-default" %></td>
        <td><%= link_to 'Edit', edit_manager_path(manager), :class => "btn-xs btn-default" %></td>
        <td><%= link_to 'Delete', manager, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn-xs btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>



<%= link_to 'New Employee', new_manager_path, :class => "btn btn-default"%>
<%= link_to 'Home', root_path, :class => "btn btn-default"%>

app/views/managers/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>  

<%= link_to 'Back', managers_path, :class => "btn btn-default" %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="title">
<h1> Employee View <%= @manager.first_name %> </h1> 
</div>
<div class="view-table">
<table class="table table-responsive table-bordered ">

  <tr>
    <th>First Name</th>
    <td><%= @manager.first_name %></td>
  </tr>
   <tr>
    <th>Last Name</th>
    <td><%= @manager.last_name %></td>
  </tr>
 <tr>
    <th>Age</th>
    <td><%= @manager.age %></td>
  </tr>
   <tr>
    <th>Gender</th>
    <td><%= @manager.gender_string %></td>
  </tr>
   <tr>
    <th>Mobile Number</th> 
    <td><%= @manager.mobile_number %></td>
  </tr>
   <tr>
    <th>Home Number</th>
    <td><%= @manager.home_number %></td>
  </tr>
   <tr>
    <th>Job Title</th>
    <td><%= @manager.job_title %></td>
  </tr>
   <tr>
    <th>Address</th>
    <td><%= @manager.street_number %> <%= @manager.street_name %> <%= @manager.suburb %></td>
  </tr>





</table>

</div>


<div class="buttons">
<%= link_to 'Edit', edit_manager_path(@manager), :class => "btn btn-default" %> |
<%= link_to 'Back', managers_path, :class => "btn btn-default" %>

</div>